# Generated by Django 3.2.5 on 2021-08-01 19:51

from django.db import migrations, models
import django.db.models.deletion
import musculoskeletal_radiograph_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('sur_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=musculoskeletal_radiograph_app.models.filepath_patient)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Radiograph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.ImageField(upload_to=musculoskeletal_radiograph_app.models.filepath_radiograph)),
                ('prediction', models.CharField(max_length=255)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musculoskeletal_radiograph_app.patient')),
            ],
        ),
    ]
