# Generated by Django 3.2.5 on 2021-08-02 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musculoskeletal_radiograph_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiograph',
            name='accuracy',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
